services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        restart: always
        environment:
            POSTGRES_HOST: db
        ports:
            - "8080:8080"
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: Dockerfile.db
            args:
                POSTGRES_HOST: ${POSTGRES_HOST}
                POSTGRES_PORT: ${POSTGRES_PORT}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
